/* link ->https://www.codingninjas.com/studio/problems/subsequences-of-string_985087?leftPanelTab=0&utm_source=youtube&utm_medium=affiliate&utm_campaign=love_babbar_16
Problem Statement
Suggest Edit
You are given a string 'STR' containing lowercase English letters from a to z inclusive. Your task is to find all non-empty possible subsequences of 'STR'.
A Subsequence of a string is the one which is generated by deleting 0 or more letters from the string and keeping the rest of the letters in the same order.
Sample Input:
1 
abc
Sample Output 1:
a ab abc ac b bc c
Explanation Of Sample Input 1:
All possible subsequences of abc are :  
“a” , “b” , “c” , “ab” , “bc” , “ac”, “abc” 
Total number of subsequences = 2^n including empty string where n is size of given string 
*/

#include <bits/stdc++.h> 

void solve(string str,int pos,string output,vector<string>&ans){

	if(pos>=str.length()){
		if(output.length()>0)  // to exclude the empty string 
		{ans.push_back(output);}
		return;
	}
    // not include
	 solve(str,pos+1,output,ans);
	 //include
	 output.push_back(str[pos]);
	 solve(str,pos+1,output,ans);
     //output.pop_back();
}
vector<string> subsequences(string str){
	vector<string> ans;
	string output = "";
	int pos;
	solve(str,0,output,ans);
	return ans;
	
}
